version: "3.3"
services:
  redis:
    image: "redis:6.2.5"
    container_name: "redis"
    ports:
      - "8902:6379"
  redis-commander:
    image: "rediscommander/redis-commander:latest"
    container_name: "redis-commander"
    ports:
      - "8903:8081"
    depends_on:
      - redis
    environment:
      VIEW_JSON_DEFAULT: "all"
      REDIS_HOSTS: "local:redis:6379"
  mongo:
    image: "mongo:5.0.9"
    container_name: "mongo"
    ports:
      - "8904:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
  mongo-express:
    image: "mongo-express:0.54"
    container_name: "mongo-express"
    ports:
      - "8905:8081"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://root:test@mongo:27017/
